version: '3.7'
services:
  spark-master:
    image: bitnami/spark:latest
    ports:
      - "8080:8080"
      - "7077:7077"
    deploy:
      placement:
        constraints: [node.role == manager]
  spark-worker:
    image: bitnami/spark:latest
    deploy:
      replicas: 2
      placement:
        constraints: [node.role == worker]

